import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>


      <nav className='navbar h-10 flex justify-start'>
        <Link className='navitem bg-blue-500 text-white hover:bg-blue-700 rounded flex items-center px-4' href="/">home</Link>
        <Link className='navitem bg-blue-500 text-white hover:bg-blue-700 rounded flex items-center px-4' href="/posts">posts</Link>
      </nav>


      {children}
      </body>
    </html>
  )
}
